logger:
  savePath: 'log'
  maxSize: 5
  maxAge: 400
  maxBackups: 1000
  isCompress: true
  logLevel: 'debug'

database:
  mysql:
    addr: xxx
    port: 3306
    username: root
    password: 'password'
    db: zhihu
    charset: utf8mb4
    connMaxIdleTime: '180s'
    connMaxLifeTime: '1800s'
    maxIdleConns: 100
    maxOpenConns: 500
  redis:
    addr: xxx
    port: 6379
    username: ''
    password: password
    db: 1
    poolSize: 10000

app:
  cookie:
    secret: yWa6!tEAVtz2131234vcertve5%&t2mUgU!3XCM3PD85!XmM^tcQBwsWByWL
    domain: 'zhihu.com'
    maxAge: 604800
    secure: true
    httpOnly: true
    sameSite: 1

server:
  mode: debug
  port: 8080
  readTimeout: 60s
  writeTimeout: 60s

middleware:
  cors:
    mode: allow_all
    whitelist:
      - allow-origin: example1.com
        allow-headers: content-type
        allow-methods: GET, POST
        expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
        allow-credentials: true
      - allow-origin: example2.com
        allow-headers: content-type
        allow-methods: GET, POST
        expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
        allow-credentials: true


  jwt:
    secretKey: MSR2pH^N6dqqQ5Ns5x!eF4YWVpwzmb3@8RzphRFbEkRwLEra86v3LCB%PvGx$a$L
    expiresTime: 604800
    bufferTime: 86400
    issuer: 'zhihu.com'